export const baseUrl = "https://test.unknownpros.com:5000/"
export const fetchAllRooms = "FETCH_ALL_ROOMS"
export const fetchFreeRooms = "FETCH_FREE_ROOMS"
export const fetchPaidRooms = "FETCH_PAID_ROOMS"
export const addNewRoom = "ADD_NEW_ROOM"
export const getUserGames = "GET_USER_GAMES"
export const getMatchDataText = "GET_MATCH_DATA"
export const removeRoom = "REMOVE_ROOM"
