export const baseUrl = "https://test.unknownpros.com/"
export const fetchAllRooms = "FETCH_ALL_ROOMS"
export const addNewRoom = "ADD_NEW_ROOM"
export const getUserGames = "GET_USER_GAMES"
export const getMatchDataText = "GET_MATCH_DATA"
export const removeRoom = "REMOVE_ROOM"
